services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8033779980:AAECGMj1LKfMoL6ucso9tFYgB7TyHXcXm6E
      - key: WEBHOOK_URL
        fromGroup:
          name: https://telegram-bot-dmvu.onrender.com
